const { test, assert, fs, path, vm, ts, read, readPropertyPanelCss } = require("./frontend-trace.helpers");

test("library page exposes local artifact index views", () => {
  const root = path.resolve(__dirname, "../..");
  const vite = read(root, "vite.config.ts");
  const libraryHtml = read(root, "Apps/Workbench/library.html");
  const libraryEntry = read(root, "Apps/Workbench/src/library.tsx");
  const graphHtml = read(root, "Apps/Workbench/function-slot-graph.html");
  const graphEntry = read(root, "Apps/Workbench/src/function-slot-graph.tsx");
  const graphApp = read(root, "Apps/Workbench/src/components/FunctionSlotGraphApp.tsx");
  const libraryApp = read(root, "Apps/Workbench/src/components/LibraryApp.tsx");
  const app = read(root, "Apps/Workbench/src/components/WorkbenchApp.tsx");
  const api = read(root, "Apps/Workbench/src/api/client.ts");

  assert.match(vite, /library: "Apps\/Workbench\/library\.html"/);
  assert.match(vite, /functionSlotGraph: "Apps\/Workbench\/function-slot-graph\.html"/);
  assert.match(vite, /"\/function-slot-graph"/);
  assert.match(vite, /request\.url = "\/function-slot-graph\.html"/);
  assert.match(libraryHtml, /src="\/src\/library\.tsx"/);
  assert.match(graphHtml, /src="\/src\/function-slot-graph\.tsx"/);
  assert.match(libraryEntry, /<LibraryApp \/>/);
  assert.match(graphEntry, /<FunctionSlotGraphApp \/>/);
  assert.match(app, /setWorkbenchView\("library", setActiveView\)/);
  assert.match(app, /window\.location\.assign\("\/function-slot-graph"\)/);
  assert.match(app, /<LibraryApp embedded/);
  assert.match(api, /\/api\/library\/items/);
  assert.match(api, /\/api\/function-slot-library\/\$\{encodeURIComponent\(artifactId\)\}\/graph/);
  assert.match(libraryApp, /处理库/);
  assert.match(libraryApp, /\/function-slot-graph/);
  assert.match(graphApp, /GraphCanvas/);
  assert.match(graphApp, /\/full-analysis/);
  assert.match(graphApp, /\/threadpool/);
  assert.match(libraryApp, /loadLibraryItem/);
  assert.match(libraryApp, /libraryArtifactTree/);
});

test("threadpool page and shot boundary agent use proxied API surface", () => {
  const root = path.resolve(__dirname, "../..");
  const vite = read(root, "vite.config.ts");
  const app = read(root, "Apps/Workbench/src/components/WorkbenchApp.tsx");
  const workspaceView = read(root, "Apps/Workbench/src/components/workbench/WorkbenchWorkspaceView.tsx");
  const shotBoundaryFlow = read(root, "Apps/Workbench/src/hooks/useShotBoundaryFlow.ts");
  const property = read(root, "Apps/Workbench/src/components/PropertyPanel.tsx");
  const agentRunPanel = read(root, "Apps/Workbench/src/components/property-panel/AgentRunPanel.tsx");
  const cacheDialog = read(root, "Apps/Workbench/src/components/CacheDecisionDialog.tsx");
  const threadpoolHtml = read(root, "Apps/Workbench/threadpool.html");
  const threadpoolEntry = read(root, "Apps/Workbench/src/threadpool.tsx");
  const threadpoolApp = read(root, "Apps/Workbench/src/components/ThreadPoolApp.tsx");
  const threadpoolCss = read(root, "Apps/Workbench/styles/threadpool.css");
  const api = read(root, "Apps/Workbench/src/api/client.ts");

  assert.match(vite, /threadpool: "Apps\/Workbench\/threadpool\.html"/);
  assert.match(vite, /isWorkbenchRoute\(pathname\)/);
  assert.match(vite, /"\/full-analysis"/);
  assert.match(vite, /"\/library"/);
  assert.match(vite, /"\/threadpool"/);
  assert.match(vite, /request\.url = "\/index\.html"/);
  assert.match(threadpoolHtml, /src="\/src\/threadpool\.tsx"/);
  assert.match(threadpoolEntry, /<ThreadPoolApp \/>/);
  assert.match(app, /setWorkbenchView\("threadpool", setActiveView\)/);
  assert.match(app, /<ThreadPoolApp embedded/);
  assert.match(workspaceView, /workspace-grid \$\{active \? "" : "is-hidden-view"\}/);
  assert.doesNotMatch(app, /href="http:\/\/127\.0\.0\.1:5177\/threadpool"/);
  assert.match(api, /\/api\/threadpool\/roles/);
  assert.match(api, /\/api\/threadpool\/threads\/\$\{encodeURIComponent\(threadId\)\}\/conversation/);
  assert.match(api, /\/api\/sample-videos\/\$\{encodeURIComponent\(sampleVideoId\)\}\/shot-boundary/);
  assert.match(api, /\/api\/processing-jobs\/\$\{encodeURIComponent\(jobId\)\}\/cache-decision/);
  assert.match(api, /cacheDecision: options\.cacheDecision \?\? "ask"/);
  assert.match(shotBoundaryFlow, /resolveShotBoundaryCacheDecision\(prompt\.jobId, "reuse"\)/);
  assert.match(shotBoundaryFlow, /resolveShotBoundaryCacheDecision\(prompt\.jobId, "refresh"\)/);
  assert.match(shotBoundaryFlow, /jobId: job\.jobId/);
  assert.match(shotBoundaryFlow, /cache_waiting|setShotCachePrompt/);
  assert.match(api, /resolveShotBoundaryCacheDecision/);
  assert.match(api, /resolveCacheDecision/);
  assert.match(threadpoolApp, /discardThreadPoolThread/);
  assert.match(threadpoolApp, /THREADPOOL_REFRESH_INTERVAL_MS = 2000/);
  assert.match(threadpoolApp, /window\.setInterval/);
  assert.match(threadpoolApp, /getThreadConversation/);
  assert.match(threadpoolApp, /\(detail\?\.threads \?\? \[\]\)\.filter\(\(thread\) => !thread\.seed\)/);
  assert.doesNotMatch(threadpoolApp, /thread\.seed \? "seed \/ " : ""/);
  assert.match(threadpoolApp, /replenishing/);
  assert.match(threadpoolApp, /查看对话/);
  assert.match(threadpoolApp, /ThreadConversationPanel/);
  assert.match(threadpoolApp, /window\.confirm/);
  assert.match(threadpoolCss, /\.threadpool-conversation-panel/);
  assert.match(threadpoolCss, /\.threadpool-conversation-block summary/);
  assert.match(property, /AgentRunPanel/);
  assert.match(agentRunPanel, /shot-boundary/);
  assert.match(property, /onRunShotBoundary/);
  assert.match(agentRunPanel, /renderResultOrigin/);
  assert.doesNotMatch(agentRunPanel, /repairAttemptCount/);
  assert.match(agentRunPanel, /ThreadPool 获取 lease 超时，Agent turn 未提交，可重试/);
  assert.match(cacheDialog, /发现切镜缓存/);
  assert.match(cacheDialog, /发现脚本段落缓存/);
  assert.match(cacheDialog, /fps \/ \{item\.shotCount \?\? "\?"\} 镜 \/ turn/);
  assert.match(agentRunPanel, /SHOT_BOUNDARY_GUARD_POLL_MS = 2000/);
  assert.match(agentRunPanel, /setTimeout\(\(\) => syncGuard\(false\), SHOT_BOUNDARY_GUARD_POLL_MS\)/);
  assert.match(agentRunPanel, /job\.stage === "shot\.boundary_transform\.thread_acquire"/);
  assert.match(agentRunPanel, /!jobTurnId/);
  assert.match(api, /\/api\/sample-videos\/\$\{encodeURIComponent\(sampleVideoId\)\}\/shot-boundary/);
});

test("workbench helper labels transform thread acquire as waiting lease", () => {
  const root = path.resolve(__dirname, "../..");
  const helpers = read(root, "Apps/Workbench/src/utils/workbenchHelpers.ts");

  assert.match(helpers, /"shot\.boundary_transform\.thread_acquire": "等待 Transform lease"/);
});

test("property panel treats processed passed single-shot data as valid unless it matches legacy fallback", () => {
  const root = path.resolve(__dirname, "../..");
  const formatters = read(root, "Apps/Workbench/src/components/property-panel/formatters.ts");
  const agentRunPanel = read(root, "Apps/Workbench/src/components/property-panel/AgentRunPanel.tsx");

  assert.match(formatters, /return shots\.length > 0;/);
  assert.match(agentRunPanel, /hasValidShotResult \? `\$\{analysis\.shots\.length\} 镜 \/ \$\{analysis\.boundaries\?\.length \?\? 0\} 边界` : "无有效切镜结果"/);
  assert.match(agentRunPanel, /analysis && !hasValidShotResult \? <div className="detail-hint">无有效切镜结果 \/ 需重新分析<\/div> : null/);
});

test("subtitle autosave uses queued save tokens and forwards revision preconditions", () => {
  const root = path.resolve(__dirname, "../..");
  const subtitleFlow = read(root, "Apps/Workbench/src/hooks/useSubtitleDraftFlow.ts");
  const api = read(root, "Apps/Workbench/src/api/client.ts");
  const types = read(root, "Apps/Workbench/src/types.ts");

  assert.match(subtitleFlow, /subtitleSaveQueueRef = useRef\(Promise\.resolve\(true\)\)/);
  assert.match(subtitleFlow, /subtitleSaveTokenRef = useRef\(0\)/);
  assert.match(subtitleFlow, /expectedSubtitleArtifactId: subtitles\.artifactId \?\? null/);
  assert.match(subtitleFlow, /expectedRevisionIndex: subtitles\.revisionIndex \?\? null/);
  assert.match(subtitleFlow, /code === "subtitle_revision_conflict"/);
  assert.match(subtitleFlow, /saveToken: draft\.saveToken \?\? null/);
  assert.match(api, /expectedSubtitleArtifactId: options\.expectedSubtitleArtifactId \?\? null/);
  assert.match(api, /expectedRevisionIndex: options\.expectedRevisionIndex \?\? null/);
  assert.match(types, /saveToken\?: number \| null;/);
  assert.match(types, /queuedAt\?: number \| null;/);
});

test("workbench exposes commerce brief summary and visible content profile inputs", () => {
  const root = path.resolve(__dirname, "../..");
  const property = read(root, "Apps/Workbench/src/components/PropertyPanel.tsx");
  const types = read(root, "Apps/Workbench/src/types.ts");
  const css = readPropertyPanelCss(root);
  const roles = read(root, "Infrastructure/ThreadPool/thread_roles.json");

  assert.match(types, /commerceBrief\?: \{/);
  assert.match(types, /sellingObject: string;/);
  assert.match(css, /\.commerce-brief-panel/);
  assert.match(roles, /"script-segment-analyzer"/);
  assert.match(roles, /"script-segment-analyzer"[\s\S]*"min_idle": 3/);
  assert.doesNotMatch(property, /CommerceBriefPanel/);
});

test("workbench understand flow triggers script segment analysis", () => {
  const root = path.resolve(__dirname, "../..");
  const app = read(root, "Apps/Workbench/src/components/WorkbenchApp.tsx");
  const helpers = read(root, "Apps/Workbench/src/utils/workbenchHelpers.ts");
  const analysisFlow = read(root, "Apps/Workbench/src/hooks/useAnalysisJobFlow.ts");
  const api = read(root, "Apps/Workbench/src/api/client.ts");
  const server = read(root, "Apps/Api/server.js");
  const registry = read(root, "Apps/Api/lib/compatibility/analysis-role-registry.js");
  const index = read(root, "Infrastructure/ArtifactIndex/artifact-index.js");

  assert.match(app, /const handleUnderstand = useCallback\(async \(\) =>/);
  assert.match(app, /scriptSegmentFlow\.run\("ask"\)/);
  assert.match(analysisFlow, /runAnalysisRole/);
  assert.match(analysisFlow, /getAnalysisRole/);
  assert.match(app, /const handleUnderstand = useCallback\(async \(\) =>/);
  assert.match(helpers, /startAnalysisRole/);
  assert.match(helpers, /runAnalysisRole/);
  assert.match(helpers, /expectedShotBoundaryArtifactId: state\.sampleArtifact\?\.shotBoundaryAnalysis\?\.artifactId \?\? null/);
  assert.match(read(root, "Apps/Workbench/src/utils/analysisRoles.ts"), /"script_segment\.cache_lookup": "检查脚本段落缓存"/);
  assert.match(read(root, "Apps/Workbench/src/utils/analysisRoles.ts"), /"script_segment\.cache_reuse": "复用脚本段落缓存"/);
  assert.match(read(root, "Apps/Workbench/src/utils/analysisRoles.ts"), /"script_segment\.input_prepare": "准备脚本段落输入"/);
  assert.match(read(root, "Apps/Workbench/src/utils/analysisRoles.ts"), /"script_segment\.input_package": "生成脚本段落输入包"/);
  assert.match(read(root, "Apps/Workbench/src/utils/analysisRoles.ts"), /"script_segment\.repair": "修复脚本段落结果"/);
  assert.match(api, /getAnalysisRoles/);
  assert.match(api, /\/api\/sample-videos\/\$\{encodeURIComponent\(sampleVideoId\)\}\/analyses\/\$\{encodeURIComponent\(analysisId\)\}/);
  assert.match(api, /cacheDecision: options\.cacheDecision \?\? "ask"/);
  assert.match(api, /expectedShotBoundaryArtifactId: options\.expectedShotBoundaryArtifactId \?\? null/);
  assert.match(read(root, "Apps/Api/lib/modules/catalog.js"), /createScriptSegmentAnalysisDefinition/);
  assert.match(registry, /MODULE_DEFINITIONS\.filter\(\(definition\) => definition\.moduleKind === "structure-analysis"\)/);
  assert.match(read(root, "Apps/Api/lib/compatibility/analysis-role-definition.js"), /expectedShotBoundaryArtifactId: dependencies\.shotBoundaryArtifactId \?\? body\?\.expectedShotBoundaryArtifactId \?\? null/);
  assert.match(server, /\/api\/analysis-roles/);
  assert.match(server, /startLegacyAnalysis/);
  assert.match(server, /script-segments/);
  assert.match(index, /script_segment\.materialize/);
  assert.match(index, /"script-segment-analysis": "脚本段落"/);
});

test("workbench removes create input view entry", () => {
  const root = path.resolve(__dirname, "../..");
  const app = read(root, "Apps/Workbench/src/components/WorkbenchApp.tsx");
  const property = read(root, "Apps/Workbench/src/components/PropertyPanel.tsx");
  const view = read(root, "Apps/Workbench/src/utils/workbenchView.ts");

  assert.match(view, /"workspace" \| "full-analysis" \| "library" \| "threadpool"/);
  assert.doesNotMatch(view, /\/create/);
  assert.doesNotMatch(app, /创作输入/);
  assert.doesNotMatch(app, /CreateInputApp/);
  assert.doesNotMatch(property, /profile-form/);
});

test("property panel shows all shots and recent shot analysis history", () => {
  const root = path.resolve(__dirname, "../..");
  const propertyPanel = read(root, "Apps/Workbench/src/components/PropertyPanel.tsx");
  const property = read(root, "Apps/Workbench/src/components/property-panel/AgentRunPanel.tsx");
  const scriptPanel = read(root, "Apps/Workbench/src/components/property-panel/ScriptSegmentPanel.tsx");
  const rhythmPanel = read(root, "Apps/Workbench/src/components/property-panel/RhythmStructurePanel.tsx");
  const packagingPanel = read(root, "Apps/Workbench/src/components/property-panel/PackagingStructurePanel.tsx");
  const formatters = read(root, "Apps/Workbench/src/components/property-panel/formatters.ts");
  const app = read(root, "Apps/Workbench/src/components/WorkbenchApp.tsx");
  const workspaceView = read(root, "Apps/Workbench/src/components/workbench/WorkbenchWorkspaceView.tsx");
  const css = readPropertyPanelCss(root);
  const types = read(root, "Apps/Workbench/src/types.ts");

  assert.match(propertyPanel, /export type PropertyPanelTab = "shot" \| "script" \| "rhythm" \| "packaging" \| "atomization" \| "meta"/);
  assert.match(propertyPanel, /const \[internalActiveTab, setInternalActiveTab\] = useState<PropertyPanelTab>\("shot"\)/);
  assert.match(propertyPanel, /const activeTab = props\.activeTab \?\? internalActiveTab/);
  assert.match(propertyPanel, /role="tablist"/);
  assert.match(propertyPanel, /shot/);
  assert.match(propertyPanel, /script/);
  assert.match(propertyPanel, /节奏结构/);
  assert.match(propertyPanel, /包装结构/);
  assert.match(propertyPanel, /原子化/);
  assert.match(propertyPanel, /<PackagingStructurePanel/);
  assert.match(propertyPanel, /<FunctionSlotAtomizationPanel/);
  assert.match(packagingPanel, /agentName="packaging-structure"/);
  assert.match(packagingPanel, /整体包装/);
  assert.match(packagingPanel, /shotPackagingNotes/);
  assert.match(packagingPanel, /packagingBlocks/);
  assert.match(propertyPanel, /<ScriptSegmentPanel/);
  assert.match(propertyPanel, /<RhythmStructurePanel/);
  assert.doesNotMatch(property, /\.shots\.slice\(0, 12\)/);
  assert.match(property, /`\$\{analysis\.shots\.length\} 镜 \/ \$\{analysis\.boundaries\?\.length \?\? 0\} 边界`/);
  assert.match(property, /analysis\.shots\.map\(\(shot\) => \(/);
  assert.match(scriptPanel, /agentName="script-segment"/);
  assert.doesNotMatch(scriptPanel, /segmentCount：/);
  assert.doesNotMatch(scriptPanel, /resultOrigin：/);
  assert.doesNotMatch(scriptPanel, /cacheKey：/);
  assert.doesNotMatch(scriptPanel, /sourceTurn：/);
  assert.doesNotMatch(scriptPanel, /repairAttemptCount：/);
  assert.match(scriptPanel, /onSelectSegment/);
  assert.match(scriptPanel, /agent-script-meta/);
  assert.match(scriptPanel, /运行脚本段落分析|运行/);
  assert.match(rhythmPanel, /agentName="rhythm-structure"/);
  assert.doesNotMatch(rhythmPanel, /cardCount：/);
  assert.match(rhythmPanel, /sectionCount：/);
  assert.match(rhythmPanel, /rhythm-overview-panel/);
  assert.match(rhythmPanel, /整体节奏/);
  assert.doesNotMatch(rhythmPanel, /观感作用/);
  assert.doesNotMatch(rhythmPanel, /迁移规则/);
  assert.match(rhythmPanel, /analysis\.overview\.summary/);
  assert.match(rhythmPanel, /analysis\?\.sections/);
  assert.match(rhythmPanel, /rhythm-card-badge/);
  assert.doesNotMatch(rhythmPanel, /resultOrigin：/);
  assert.doesNotMatch(rhythmPanel, /cacheKey：/);
  assert.doesNotMatch(rhythmPanel, /sourceTurn：/);
  assert.doesNotMatch(rhythmPanel, /repairAttemptCount：/);
  assert.match(rhythmPanel, /onSelectCard/);
  assert.match(workspaceView, /currentShot=\{currentShot\}/);
  assert.match(workspaceView, /currentShotId=\{currentShotId\}/);
  assert.match(workspaceView, /scriptSegmentAnalysis=\{state\.sampleArtifact\?\.scriptSegmentAnalysis \?\? null\}/);
  assert.match(workspaceView, /scriptSegmentAnalysisHistory=\{state\.sampleArtifact\?\.scriptSegmentAnalysisHistory \?\? null\}/);
  assert.match(workspaceView, /scriptSegmentJob=\{scriptSegmentFlow\.job\}/);
  assert.match(workspaceView, /rhythmStructureJob=\{rhythmStructureFlow\.job\}/);
  assert.match(workspaceView, /packagingStructureAnalysis=\{state\.sampleArtifact\?\.packagingStructureAnalysis \?\? null\}/);
  assert.match(workspaceView, /packagingStructureAnalysisHistory=\{state\.sampleArtifact\?\.packagingStructureAnalysisHistory \?\? null\}/);
  assert.match(workspaceView, /packagingStructureJob=\{packagingStructureFlow\.job\}/);
  assert.match(app, /scriptSegmentFlow\.cachePrompt/);
  assert.match(app, /rhythmStructureFlow\.cachePrompt/);
  assert.match(app, /packagingStructureFlow\.cachePrompt/);
  assert.match(workspaceView, /onRunScriptSegment=\{/);
  assert.match(workspaceView, /onRunRhythmStructure=\{/);
  assert.match(workspaceView, /onRunPackagingStructure=\{/);
  assert.match(workspaceView, /onSelectScriptSegment=\{/);
  assert.match(workspaceView, /onSelectRhythmCard=\{/);
  assert.match(workspaceView, /onSelectPackagingBlock=\{/);
  assert.match(property, /aria-current=\{currentShotId === shot\.id \? "true" : undefined\}/);
  assert.match(property, /className=\{`agent-shot-item \$\{currentShotId === shot\.id \? "active" : ""\}`\}/);
  assert.match(property, /resolveShotSummary\(currentShot\)/);
  assert.match(property, /formatSecondsCompact\(currentShot\.start\)\} - \{formatSecondsCompact\(currentShot\.end\)/);
  assert.doesNotMatch(property, /resolveShotEndBoundaryReason/);
  assert.match(formatters, /shot\.summary \?\? shot\.reason/);
  assert.match(workspaceView, /shotBoundaryAnalysisHistory=\{state\.sampleArtifact\?\.shotBoundaryAnalysisHistory \?\? null\}/);
  assert.match(property, /historyEntries\.slice\(-5\)\.reverse\(\)\.map/);
  assert.match(property, /className=\{`agent-history-item \$\{analysis\?\.artifactId === entry\.artifactId \? "is-current" : ""\}`\}/);
  assert.match(css, /\.agent-shot-list[\s\S]*max-height: 220px;[\s\S]*overflow: auto;/);
  assert.match(css, /\.agent-shot-current/);
  assert.match(css, /\.agent-shot-item\.active,\s*[\s\S]*\.agent-shot-item\[aria-current="true"\]/);
  assert.match(css, /\.property-tabs/);
  assert.match(css, /flex: 0 0 clamp\(84px, 31%, 128px\)/);
  assert.match(css, /\.property-tab\.active,\s*[\s\S]*\.property-tab\[aria-selected="true"\]/);
  assert.match(css, /\.agent-shot-summary/);
  assert.match(css, /\.agent-history-list[\s\S]*max-height: 160px;[\s\S]*overflow: auto;/);
  assert.match(css, /\.agent-script-item/);
  assert.match(types, /shotBoundaryAnalysisHistory\?: ShotBoundaryAnalysisHistoryEntry\[] \| null;/);
  assert.match(types, /scriptSegmentAnalysisHistory\?: ScriptSegmentHistoryEntry\[] \| null;/);
  assert.match(types, /cacheKind\?: "sample" \| "shot_boundary" \| "script_segment" \| "rhythm_structure" \| "packaging_structure" \| "function_slot_atomization" \| string;/);
  assert.match(types, /segmentCount\?: number \| null;/);
  assert.match(types, /sectionCount\?: number \| null;/);
  assert.match(types, /cardCount\?: number \| null;/);
  assert.match(types, /sourceSegmentId: string;/);
  assert.match(types, /summary\?: string \| null;/);
  assert.match(types, /endBoundaryReason\?: string \| null;/);
  assert.match(types, /scriptSegmentAnalysis\?: ScriptSegmentArtifact \| null;/);
  assert.match(types, /rhythmStructureAnalysis\?: RhythmStructureArtifact \| null;/);
  assert.match(types, /packagingStructureAnalysis\?: PackagingStructureArtifact \| null;/);
});

test("agent cards show readable activity and timeline traces across agent turns", () => {
  const root = path.resolve(__dirname, "../..");
  const types = read(root, "Apps/Workbench/src/types.ts");
  const jobTypes = read(root, "Apps/Workbench/src/types/job.ts");
  const shotPanel = read(root, "Apps/Workbench/src/components/property-panel/AgentRunPanel.tsx");
  const scriptPanel = read(root, "Apps/Workbench/src/components/property-panel/ScriptSegmentPanel.tsx");
  const rhythmPanel = read(root, "Apps/Workbench/src/components/property-panel/RhythmStructurePanel.tsx");
  const packagingPanel = read(root, "Apps/Workbench/src/components/property-panel/PackagingStructurePanel.tsx");
  const atomizationPanel = read(root, "Apps/Workbench/src/components/property-panel/FunctionSlotAtomizationPanel.tsx");
  const timelinePanel = read(root, "Apps/Workbench/src/components/property-panel/AgentTurnTimeline.tsx");
  const traceCards = read(root, "Apps/Workbench/src/components/property-panel/agentTraceCards.ts");
  const css = readPropertyPanelCss(root);

  assert.match(types, /activeThreadMessage\?: \{/);
  assert.match(types, /agentActivity\?: AgentActivitySummary \| null;/);
  assert.match(jobTypes, /export type AgentTraceCard = \{/);
  assert.match(jobTypes, /agentTraceCards\?: AgentTraceCard\[] \| null;/);
  assert.match(jobTypes, /export type AgentTimelineItem = \{/);
  assert.match(jobTypes, /latestMessagePreview: string \| null;/);
  assert.match(types, /agentRun\?: \{/);
  assert.match(shotPanel, /AgentTurnTimelinePanel/);
  assert.match(scriptPanel, /AgentTurnTimelinePanel/);
  assert.match(rhythmPanel, /AgentTurnTimelinePanel/);
  assert.match(packagingPanel, /AgentTurnTimelinePanel/);
  assert.match(atomizationPanel, /AgentTurnTimelinePanel/);
  assert.match(timelinePanel, /resolveAgentTraceCards\(job\)/);
  assert.match(timelinePanel, /getAgentTurnTimeline\(selectedCard\.threadId as string, selectedCard\.turnId as string\)/);
  assert.match(timelinePanel, /setInterval\([\s\S]*2000/);
  assert.match(timelinePanel, /className="agent-trace-card-list"/);
  assert.match(timelinePanel, /card\.latestMessagePreview/);
  assert.match(traceCards, /shotBoundaryTransform/);
  assert.match(traceCards, /fromActivityOnly\(job\)/);
  assert.doesNotMatch(scriptPanel, /!job\.agentRun\?\.threadId \|\| !job\.agentRun\?\.turnId/);
  assert.doesNotMatch(rhythmPanel, /!job\.agentRun\?\.threadId \|\| !job\.agentRun\?\.turnId/);
  assert.doesNotMatch(packagingPanel, /!job\.agentRun\?\.threadId \|\| !job\.agentRun\?\.turnId/);
  assert.doesNotMatch(shotPanel, /message\.turnId && message\.turnId !== job\.agentRun\.turnId/);
  assert.doesNotMatch(scriptPanel, /message\.turnId && message\.turnId !== job\.agentRun\.turnId/);
  assert.doesNotMatch(rhythmPanel, /message\.turnId && message\.turnId !== job\.agentRun\.turnId/);
  assert.doesNotMatch(packagingPanel, /message\.turnId && message\.turnId !== job\.agentRun\.turnId/);
  assert.doesNotMatch(shotPanel, /className="agent-thread-message"/);
  assert.match(timelinePanel, /className="agent-latest-activity"/);
  assert.match(timelinePanel, /className="agent-turn-timeline"/);
  assert.match(css, /\.agent-trace-card-list/);
  assert.match(css, /\.agent-trace-card\.active/);
  assert.match(css, /\.agent-thread-message/);
  assert.match(css, /\.agent-summary-card/);
  assert.match(css, /\.agent-timeline-list/);
});
