const { test, assert, path, read, readWorkbenchApi } = require("./frontend-trace.helpers");

test("agent chat page is routed through appserver with ThreadPool fork timeline", () => {
  const root = path.resolve(__dirname, "../..");
  const app = read(root, "Apps/Workbench/src/components/WorkbenchApp.tsx");
  const view = read(root, "Apps/Workbench/src/utils/workbenchView.ts");
  const api = readWorkbenchApi(root);
  const chat = read(root, "Apps/Workbench/src/components/AgentChatApp.tsx");
  const chatPanels = read(root, "Apps/Workbench/src/components/agent-chat/AgentChatPanels.tsx");
  const chatModel = read(root, "Apps/Workbench/src/components/agent-chat/agentChatModel.ts");
  const css = read(root, "Apps/Workbench/styles/agent-chat.css");
  const styles = read(root, "Apps/Workbench/styles.css");

  assert.match(view, /"agent-chat"/);
  assert.match(view, /pathname === "\/agent-chat"/);
  assert.match(app, /AgentChatApp/);
  assert.match(app, /setWorkbenchView\("agent-chat", setActiveView\)/);
  assert.match(app, /Agent 对话/);
  assert.match(api, /\/api\/agent-chat\/threads/);
  assert.match(api, /\/api\/agent-chat\/threads\/\$\{encodeURIComponent\(threadId\)\}\/turns/);
  assert.match(api, /stopAgentChatTurn/);
  assert.match(api, /retryAgentChatTurn/);
  assert.match(api, /listActiveTurns/);
  assert.match(api, /stopActiveTurn/);
  assert.match(api, /stopActiveThread/);
  assert.match(api, /retryActiveTurn/);
  assert.match(api, /\/api\/active-turns\/\$\{encodeURIComponent\(bindingId\)\}\/stop-thread/);
  assert.match(api, /\/api\/active-turns/);
  assert.match(api, /\/api\/agent-chat\/threads\/\$\{encodeURIComponent\(threadId\)\}\/compact/);
  assert.match(read(root, "Apps/Api/lib/gateways/appserver/bridge.js"), /compactThread/);
  assert.match(read(root, "Apps/Api/lib/gateways/appserver/bridge.py"), /client\.compact_thread/);
  assert.match(read(root, "Infrastructure/AgentRuntime/agent_runtime/appserver/client.py"), /"turn\/interrupt"/);
  assert.doesNotMatch(read(root, "Infrastructure/AgentRuntime/agent_runtime/appserver/client.py"), /"turn\/cancel"/);
  assert.match(api, /\/api\/agent-chat\/threads\/\$\{encodeURIComponent\(threadId\)\}\/turns\/\$\{encodeURIComponent\(turnId\)\}\/timeline/);
  assert.match(api, /\/api\/agent-chat\/conversations/);
  assert.match(api, /\/api\/agent-chat\/conversations\/\$\{encodeURIComponent\(conversationId\)\}\/resume/);
  assert.match(api, /\/api\/agent-chat\/conversations\/\$\{encodeURIComponent\(conversationId\)\}\/archive/);
  assert.match(api, /\/api\/agent-chat\/conversations\/\$\{encodeURIComponent\(conversationId\)\}\/confirm/);
  assert.match(api, /\/api\/agent-chat\/conversations\/\$\{encodeURIComponent\(conversationId\)\}\/dialogue-review/);
  assert.match(api, /\/api\/agent-chat\/conversations\/\$\{encodeURIComponent\(conversationId\)\}\/dialogue-rework/);
  assert.match(api, /\/api\/agent-chat\/conversations\/\$\{encodeURIComponent\(conversationId\)\}\/system-messages/);
  assert.match(api, /\/api\/agent-chat\/threadpool\/leases\/release/);
  assert.match(chat, /ThreadPool Role Fork/);
  assert.match(chat, /actionProjection/);
  assert.match(chat, /停止 Turn/);
  assert.doesNotMatch(chat, /停止 Thread/);
  assert.doesNotMatch(chat, /同线程重试/);
  assert.doesNotMatch(chat, /新线程重试/);
  assert.doesNotMatch(chat, /ActiveTurnsView/);
  assert.doesNotMatch(chat, /listActiveTurns/);
  assert.match(chat, /useResizableThreePaneLayout/);
  assert.match(chat, /agent-chat:layout/);
  assert.match(chat, /leftCssVar: "--agent-chat-list-width"/);
  assert.match(chat, /rightCssVar: "--agent-chat-timeline-width"/);
  assert.match(chat, /leftRatio: \{ min: 0\.1, max: 0\.22 \}/);
  assert.match(chat, /rightRatio: \{ min: 0\.1, max: 0\.4 \}/);
  assert.match(chat, /SplitResizeHandle/);
  assert.match(chat, /agent-chat-session-meta/);
  assert.match(chat, /agent-chat-conversations/);
  assert.match(chat, /agent-chat-left-resizer/);
  assert.match(chat, /agent-chat-right-resizer/);
  assert.match(chat, /重组会话/);
  assert.match(chat, /handleResumeConversation/);
  assert.match(chat, /handleArchiveConversation/);
  assert.match(chat, /creatingDraftConversationRef/);
  assert.match(chat, /creatingDraftConversationRef\.current = true/);
  assert.match(chat, /!items\.length \|\| creatingDraftConversationRef\.current/);
  assert.match(chat, /creatingDraftConversationRef\.current = false/);
  assert.match(chat, /activeConversationInvalidated/);
  assert.match(chat, /activeConversationRevision/);
  assert.match(chat, /syncActiveConversationForRetry/);
  assert.match(chat, /会话已更新，自动同步中/);
  assert.match(chat, /isAssistantTurnRunning/);
  assert.match(chat, /恢复 turn 状态中/);
  assert.match(chat, /schedulePoll\(session, currentTurnId\)/);

  const workbench = read(root, "Apps/Workbench/src/components/WorkbenchApp.tsx");
  const activeTurns = read(root, "Apps/Workbench/src/components/ActiveTurnsApp.tsx");
  const activeTurnsCss = read(root, "Apps/Workbench/styles/active-turns.css");
  assert.match(workbench, /ActiveTurnsApp/);
  assert.match(workbench, /activeView === "active-turns"/);
  assert.match(workbench, /运行面板/);
  assert.match(activeTurns, /listActiveTurns/);
  assert.match(activeTurns, /stopActiveTurn/);
  assert.match(activeTurns, /stopActiveThread/);
  assert.match(activeTurns, /retryActiveTurn/);
  assert.match(activeTurns, /actionProjection\?\.flags\?\.stopTurn/);
  assert.match(activeTurns, /actionProjection\?\.flags\?\.retrySameThread/);
  assert.match(activeTurns, /actionProjection\?\.flags\?\.retryNewThread/);
  assert.match(activeTurns, /结束 Thread/);
  assert.match(activeTurns, /新 Thread 重试/);
  assert.match(activeTurns, /mode: "new_thread"/);
  assert.match(activeTurns, /processing-job/);
  assert.match(activeTurnsCss, /active-turns-shell/);
  assert.match(chat, /会话已同步，重试发送/);
  assert.match(chat, /会话已同步，重试归档/);
  assert.match(chat, /会话已同步，重试确认/);
  assert.match(chat, /ensureSession\(false(?:, isCurrentAction)?\)/);
  assert.match(chat, /thread 已不可读，此会话已失效/);
  assert.match(chat, /expectedRevision: activeConversationRevision/);
  assert.match(chat, /isConversationConflictError/);
  assert.match(chat, /confirmAgentChatConversation/);
  assert.match(chat, /activeConversationConfirmedPlan/);
  assert.match(chat, /agent-chat-state-badge/);
  assert.match(chat, /messagesFromConversation/);
  assert.match(chat, /persistedMessages\.length \? persistedMessages : refreshedMessages/);
  assert.match(chatModel, /isAgentChatBootstrapTurn/);
  assert.match(chatModel, /初始化阶段阅读/);
  assert.match(chat, /function-slot-restructure/);
  assert.match(chat, /function-slot-shot-design/);
  assert.match(chat, /reviewAgentChatDialogue/);
  assert.match(chat, /submitAgentChatDialogueRework/);
  assert.match(chat, /submitDialogueReworkFromReview/);
  assert.match(chat, /审查台词/);
  assert.match(chat, /按审查返工/);
  assert.match(chat, /台词审查中/);
  assert.match(chat, /台词审查建议返工，正在提交返工/);
  assert.match(chat, /composerLocked/);
  assert.match(chat, /dialogueActionLocked/);
  assert.match(chat, /DialogueReviewSummary/);
  assert.match(chat, /resolveCurrentShotDesignFinalPath/);
  assert.match(chat, /attachDialogueReviewToMessages/);
  assert.match(chat, /dialogueRoboticReview/);
  assert.match(chat, /确认此方案/);
  assert.match(chat, /重新确认/);
  assert.match(chat, /canConfirmRestructure/);
  assert.doesNotMatch(chat, /activeConversationConfirmedPlan\?\.turnId !== currentTurnId/);
  assert.doesNotMatch(chat, /DEFAULT_RESTRUCTURE_FINAL_PATH/);
  assert.match(chat, /resolveCurrentRestructureFinalPath/);
  assert.match(chat, /normalizeRestructureFinalPath/);
  assert.match(chat, /buildConfirmationId/);
  assert.match(chat, /confirmationId/);
  assert.match(chat, /sourceRestructurePath/);
  assert.match(chat, /restructureFinalPath: sourceRestructurePath/);
  assert.doesNotMatch(chat, /autoRunRestructureDisplayTransform/);
  assert.match(chat, /autoRunShotStoryboardPrep/);
  assert.doesNotMatch(chat, /结构展示转换/);
  assert.match(chat, /startAgentChatThread/);
  assert.match(chat, /sendAgentChatMessage/);
  assert.match(chat, /compactAgentChatThread/);
  assert.match(chatPanels, /agent-chat-context-usage/);
  assert.match(chatPanels, /% used/);
  assert.match(chat, /正在压缩上下文/);
  assert.match(chat, /buildContextUsageKey/);
  assert.match(chat, /collectAgentChatTurn/);
  assert.match(chat, /getAgentChatTurnTimeline/);
  assert.match(chat, /releaseAgentChatLease/);
  assert.doesNotMatch(chat, /conversationId: activeConversationId/);
  const startThreadCall = chat.match(/startAgentChatThread\(\{[\s\S]*?\}\);/)?.[0] ?? "";
  assert.doesNotMatch(startThreadCall, /conversationId/);
  assert.doesNotMatch(startThreadCall, /expectedRevision/);
  assert.match(chat, /payload\.deleted/);
  assert.match(chat, /lease 已释放，会话已删除/);
  assert.match(chat, /disabled=\{busy\} onClick=\{handleRelease\}/);
  assert.match(chat, /event\.key !== "Enter" \|\| event\.ctrlKey/);
  assert.match(chat, /event\.preventDefault\(\)/);
  assert.match(chat, /agent-chat-timeline/);
  assert.match(chatPanels, /agent-chat-timeline-list/);
  assert.match(chat, /rightPanelTab/);
  assert.match(chat, /Slot\/Atom/);
  assert.match(chat, /SlotAtomView/);
  assert.match(chat, /slotAtomDisplay/);
  assert.match(chat, /resolveActiveSlotAtomDisplay/);
  assert.doesNotMatch(chat, /className="agent-timeline-list"/);
  const graphLayouts = read(root, "Apps/Workbench/src/components/function-slot-graph/graphLayouts.ts");
  assert.match(graphLayouts, /node\.type === "sourceVariant"\) return filters\.sourceVariant/);
  assert.doesNotMatch(graphLayouts, /if \(node\.type === "sourceVariant"\) return true/);
  assert.match(css, /\.agent-chat-layout/);
  assert.match(css, /--agent-chat-list-width/);
  assert.match(css, /--agent-chat-timeline-width/);
  assert.match(css, /grid-template-columns: var\(--agent-chat-list-width, 260px\) 10px minmax\(520px, 1fr\) 10px var\(--agent-chat-timeline-width, 420px\)/);
  assert.match(css, /\.agent-chat-conversations/);
  assert.match(css, /\.agent-chat-resizer/);
  assert.match(css, /\.agent-chat-session-meta/);
  assert.match(css, /\.agent-chat-context-usage/);
  assert.match(css, /\.agent-chat-dialogue-review/);
  assert.match(css, /\.agent-chat-dialogue-review\.rework/);
  assert.match(css, /conic-gradient/);
  assert.match(css, /--context-progress/);
  assert.match(css, /\.agent-chat-timeline \{[\s\S]*grid-template-rows: auto minmax\(0, 1fr\)[\s\S]*height: 100%/);
  assert.match(css, /\.agent-chat-timeline-list \{[\s\S]*min-height: 0;[\s\S]*overflow: auto/);
  assert.match(css, /\.agent-chat-side-tabs/);
  assert.match(css, /\.agent-chat-slot-atom-panel/);
  assert.match(css, /\.agent-chat-slot-list/);
  assert.match(css, /\.agent-chat-atom-card/);
  assert.match(styles, /agent-chat\.css/);
});

test("new UI restructure process pseudo streaming is scoped to the active turn", () => {
  const root = path.resolve(__dirname, "../..");
  const restructure = [
    "Apps/Workbench/src/components/new-ui/NewUiRestructureWorkspace.tsx",
    "Apps/Workbench/src/components/new-ui/restructureWorkspacePseudoStream.ts",
  ].map((file) => read(root, file)).join("\n");
  const processHook = restructure.match(/function usePseudoStreamedProcessMessages[\s\S]*?function startPseudoStream/)?.[0] ?? "";

  assert.match(restructure, /usePseudoStreamedProcessMessages\([\s\S]*activeTurnId: activeTurnTarget\?\.turnId/);
  assert.match(restructure, /pendingAssistantTurnId: pendingAssistantMessage\?\.turnId/);
  assert.match(processHook, /options: PseudoStreamMessageOptions/);
  assert.match(processHook, /targetTurnIds = useMemo/);
  assert.match(processHook, /targetMessageIds = useMemo/);
  assert.match(processHook, /!targetRunning \|\| !isPseudoStreamTargetMessage\(item\.message, targetTurnIds, targetMessageIds\)/);
  assert.doesNotMatch(processHook, /if \(!targetRunning\) \{[\s\S]*?return;\s*\}/);
});
